// app/layout.js
import { Open_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WishlistProvider } from "./context/WishlistContext";
import { CartProvider } from "./context/CartContext"; // Import new provider
import TopNav from "./components/TopNav";
import Footer from "./components/Footer";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <WishlistProvider>
          <CartProvider>
            <div className="sticky top-0 z-50">
              <TopNav />
            </div>
            <main>{children}</main>
            <Footer />
          </CartProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}